---
- name: "Fail if OS/Architecture is not supported"
  fail:
    msg: "Configuring containerd on {{ (ansible_os_family | lower) + '_' + (ansible_architecture | lower) }} is unsupported."
  when:
    - "(install_containerd_packages | default({}))[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] is not defined"
    - "containerd is defined"
  tags:
    - "containerd"

- name: "Disable unified_cgroup_hierarchy"
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="((:?(?!systemd\.unified_cgroup_hierarchy).)*?)"$'
    replace: 'GRUB_CMDLINE_LINUX="\1 systemd.unified_cgroup_hierarchy=0"'
  when:
    - "((ansible_os_family | lower) + '_' + (ansible_architecture | lower)) == 'redhat_x86_64'"
    - "containerd is defined"
  register: unified_cgroup_hierarchy
  tags:
    - "containerd"

- name: "Update Grub"
  shell:  "grub2-mkconfig"
  when:
    - "((ansible_os_family | lower) + '_' + (ansible_architecture | lower)) == 'redhat_x86_64'"
    - "unified_cgroup_hierarchy.changed"
    - "containerd is defined"
  notify: "reboot"
  tags:
    - "containerd"
  
- name: "Create containerd directory"
  file:
    name: "/etc/containerd"
    state: "directory"
  when:
    - "containerd is defined"
  tags:
    - "containerd"
- name: "Update templates"
  template:
    src:  "{{ item.src | default((item.dest | basename ()) + '.j2')}}"
    dest: "{{ item.dest }}"
  with_items:
    - dest:  "/etc/containerd/config.toml"
    - dest:  "/etc/modules-load.d/containerd.conf"
    - dest:  "/etc/sysctl.d/99-kubernetes-cri.conf"
  notify: "reboot"
  when:
    - "containerd is defined"
  tags:
    - "containerd"
- name: "Start and enable containerd"
  systemd:
    name: "containerd"
    state: "started"
    enabled: "yes"
    daemon_reload: "yes"
  tags:
    - "containerd"
